library/config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  resources :loans
  resources :users
  resources :zipcodes
  resources :authors
  resources :books
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#index'
end

library/app/models/zipcode.rb
class Zipcode < ApplicationRecord
    has_one :user, :dependent => :destroy
end

library/app/controllers/zipcodes_controller.rb
class ZipcodesController < ApplicationController
  before_action :set_zipcode, only: %i[ show edit update destroy ]

  # GET /zipcodes or /zipcodes.json
  def index
    @zipcodes = Zipcode.all
  end

  # GET /zipcodes/1 or /zipcodes/1.json
  def show
  end

  # GET /zipcodes/new
  def new
    @zipcode = Zipcode.new
  end

  # GET /zipcodes/1/edit
  def edit
  end

  # POST /zipcodes or /zipcodes.json
  def create
    @zipcode = Zipcode.new(zipcode_params)

    respond_to do |format|
      if @zipcode.save
        format.html { redirect_to @zipcode, notice: "Zipcode was successfully created." }
        format.json { render :show, status: :created, location: @zipcode }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @zipcode.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /zipcodes/1 or /zipcodes/1.json
  def update
    respond_to do |format|
      if @zipcode.update(zipcode_params)
        format.html { redirect_to @zipcode, notice: "Zipcode was successfully updated." }
        format.json { render :show, status: :ok, location: @zipcode }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @zipcode.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /zipcodes/1 or /zipcodes/1.json
  def destroy
    @zipcode.destroy
    respond_to do |format|
      format.html { redirect_to zipcodes_url, notice: "Zipcode was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_zipcode
      @zipcode = Zipcode.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def zipcode_params
      params.require(:zipcode).permit(:info, :city, :state)
    end
end

library/app/helpers/zipcodes_helper.rb
module ZipcodesHelper
end

library/app/views/zipcodes/_form.html.erb
<%= form_with(model: zipcode) do |form| %>
  <% if zipcode.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(zipcode.errors.count, "error") %> prohibited this zipcode from being saved:</h2>

      <ul>
        <% zipcode.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :info %>
    <%= form.text_field :info %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city %>
  </div>

  <div class="field">
    <%= form.label :state %>
    <%= form.text_field :state %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

library/app/views/zipcodes/edit.html.erb
<h1>Editing Zipcode</h1>

<%= render 'form', zipcode: @zipcode %>

<%= link_to 'Show', @zipcode %> |
<%= link_to 'Back', zipcodes_path %>

library/app/views/zipcodes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Zipcodes</h1>

<table>
  <thead>
    <tr>
      <th>Info</th>
      <th>City</th>
      <th>State</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @zipcodes.each do |zipcode| %>
      <tr>
        <td><%= zipcode.info %></td>
        <td><%= zipcode.city %></td>
        <td><%= zipcode.state %></td>
        <td><%= link_to 'Show', zipcode %></td>
        <td><%= link_to 'Edit', edit_zipcode_path(zipcode) %></td>
        <td><%= link_to 'Destroy', zipcode, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Zipcode', new_zipcode_path %>

library/app/views/zipcodes/new.html.erb
<h1>New Zipcode</h1>

<%= render 'form', zipcode: @zipcode %>

<%= link_to 'Back', zipcodes_path %>

library/app/views/zipcodes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Info:</strong>
  <%= @zipcode.info %>
</p>

<p>
  <strong>City:</strong>
  <%= @zipcode.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @zipcode.state %>
</p>

<%= link_to 'Edit', edit_zipcode_path(@zipcode) %> |
<%= link_to 'Back', zipcodes_path %>